package exporter

import (
	"fmt"
	"io"
	"strings"
)

type SQLExporter struct {
	fetcherNames []string
}

func (e *SQLExporter) ID() string            { return "sql" }
func (e *SQLExporter) FileExtension() string  { return ".sql" }
func (e *SQLExporter) SetFetchers(names []string) { e.fetcherNames = names }

func (e *SQLExporter) Start(w io.Writer, feederInfo string) error {
	fmt.Fprintln(w, "-- Generated by Go Network Scanner 1.0.0-beta1")
	fmt.Fprintln(w, "-- https://github.com/Responsible-User/GoNetworkScanner")
	fmt.Fprintln(w)

	// CREATE TABLE
	fmt.Fprint(w, "CREATE TABLE IF NOT EXISTS scan_results (\n\tid INTEGER PRIMARY KEY AUTOINCREMENT")
	for _, name := range e.fetcherNames {
		colName := strings.ReplaceAll(strings.ToLower(name), " ", "_")
		fmt.Fprintf(w, ",\n\t%s TEXT", colName)
	}
	fmt.Fprintln(w, "\n);")
	fmt.Fprintln(w)
	return nil
}

func (e *SQLExporter) WriteResult(w io.Writer, values []interface{}) error {
	fmt.Fprint(w, "INSERT INTO scan_results (")
	for i, name := range e.fetcherNames {
		if i > 0 {
			fmt.Fprint(w, ", ")
		}
		colName := strings.ReplaceAll(strings.ToLower(name), " ", "_")
		fmt.Fprint(w, colName)
	}
	fmt.Fprint(w, ") VALUES (")
	for i, v := range values {
		if i > 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "'%s'", sqlEscape(valStr(v)))
	}
	fmt.Fprintln(w, ");")
	return nil
}

func (e *SQLExporter) End(w io.Writer) error { return nil }

func sqlEscape(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
