package exporter

import (
	"fmt"
	"io"
	"strings"
	"time"
)

type TXTExporter struct {
	fetcherNames []string
	padLengths   []int
}

func (e *TXTExporter) ID() string            { return "txt" }
func (e *TXTExporter) FileExtension() string  { return ".txt" }
func (e *TXTExporter) SetFetchers(names []string) {
	e.fetcherNames = names
	e.padLengths = make([]int, len(names))
	for i, n := range names {
		e.padLengths[i] = len(n) * 3
		if e.padLengths[i] < 16 {
			e.padLengths[i] = 16
		}
	}
}

func (e *TXTExporter) Start(w io.Writer, feederInfo string) error {
	fmt.Fprintf(w, "Generated by Go Network Scanner 1.0.0-beta1\n")
	fmt.Fprintf(w, "https://github.com/Responsible-User/GoNetworkScanner\n\n")
	fmt.Fprintf(w, "Scanned %s\n", feederInfo)
	fmt.Fprintf(w, "%s\n\n", time.Now().Format("2006-01-02 15:04:05"))
	return nil
}

func (e *TXTExporter) WriteResult(w io.Writer, values []interface{}) error {
	for i, v := range values {
		padLen := 16
		if i < len(e.padLengths) {
			padLen = e.padLengths[i]
		}
		w.Write([]byte(pad(valStr(v), padLen)))
	}
	w.Write([]byte("\n"))
	return nil
}

func (e *TXTExporter) End(w io.Writer) error { return nil }

func pad(s string, length int) string {
	if len(s) >= length {
		return s
	}
	return s + strings.Repeat(" ", length-len(s))
}
