package exporter

import (
	"fmt"
	"io"
	"strings"
	"time"
)

type XMLExporter struct {
	fetcherNames []string
	ipIndex      int
}

func (e *XMLExporter) ID() string            { return "xml" }
func (e *XMLExporter) FileExtension() string  { return ".xml" }
func (e *XMLExporter) SetFetchers(names []string) {
	e.fetcherNames = names
	e.ipIndex = 0
	for i, n := range names {
		if n == "IP" {
			e.ipIndex = i
			break
		}
	}
}

func (e *XMLExporter) Start(w io.Writer, feederInfo string) error {
	fmt.Fprintln(w, `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	fmt.Fprintln(w, `<!-- Generated by Angry IP Scanner 4.0.0 -->`)
	fmt.Fprintln(w, `<!-- https://angryip.org -->`)
	fmt.Fprintf(w, "<scanning_report time=\"%s\">\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(w, "\t<feeder><![CDATA[%s]]></feeder>\n", feederInfo)
	fmt.Fprintln(w, "\t<hosts>")
	return nil
}

func (e *XMLExporter) WriteResult(w io.Writer, values []interface{}) error {
	ip := ""
	if e.ipIndex < len(values) {
		ip = valStr(values[e.ipIndex])
	}
	fmt.Fprintf(w, "\t\t<host address=\"%s\">\n", xmlEscape(ip))
	for i, v := range values {
		s := valStr(v)
		if s != "" {
			name := ""
			if i < len(e.fetcherNames) {
				name = e.fetcherNames[i]
			}
			fmt.Fprintf(w, "\t\t\t<result name=\"%s\"><![CDATA[%s]]></result>\n", xmlEscape(name), s)
		}
	}
	fmt.Fprintln(w, "\t\t</host>")
	return nil
}

func (e *XMLExporter) End(w io.Writer) error {
	fmt.Fprintln(w, "\t</hosts>")
	fmt.Fprintln(w, "</scanning_report>")
	return nil
}

func xmlEscape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}
